name: Release
on:
  release:
    types: [created, published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@master
        env:
          CGO_ENABLED: 0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          compress: 'true'
          name: 'known_hosts'
          dest: 'build'
          ldflags: '-w -s'

      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/*
